# Generated by Django 4.1.5 on 2023-01-03 18:28

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('ip1', models.CharField(max_length=20)),
                ('ip2', models.CharField(max_length=20)),
                ('ip3', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('createdon', models.DateTimeField(default=datetime.date(2023, 1, 3))),
            ],
        ),
        migrations.CreateModel(
            name='LiveIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('ip', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('date', models.DateField(default=datetime.date(2023, 1, 3))),
                ('buytime', models.TimeField()),
                ('instrument', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('buyprice', models.FloatField()),
                ('sellprice', models.FloatField()),
                ('diff', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('profitloss', models.FloatField()),
            ],
        ),
    ]
