# Generated by Django 4.1.5 on 2023-01-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_clients_client_rename_orders_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buytime',
            field=models.DateTimeField(),
        ),
    ]
