# Generated by Django 4.1.5 on 2023-01-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_order_buytime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
