# Generated by Django 4.1.5 on 2023-01-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_delete_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selltime',
            field=models.DateTimeField(null=True),
        ),
    ]
