# Generated by Django 4.1.5 on 2023-01-03 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_selltime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='createdon',
            field=models.DateField(default=datetime.date(2023, 1, 3)),
        ),
    ]
