# Generated by Django 4.1.5 on 2023-01-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_client_createdon_alter_order_buytime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ip1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='ip2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='ip3',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
