# Generated by Django 4.1.5 on 2023-01-05 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_client_ip1_alter_client_ip2_alter_client_ip3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ip1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='ip2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='ip3',
        ),
        migrations.AlterField(
            model_name='client',
            name='createdon',
            field=models.DateField(default=datetime.date(2023, 1, 5)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 5)),
        ),
    ]
