# Generated by Django 4.1.5 on 2023-01-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_client_ip1_remove_client_ip2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('login', models.TimeField(auto_now=True)),
                ('logout', models.TimeField()),
            ],
        ),
    ]
