# Generated by Django 4.1.5 on 2023-01-15 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_order_status_order_buy_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='createdon',
            field=models.DateField(default=datetime.date(2023, 1, 15)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 15)),
        ),
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(max_length=10),
        ),
    ]
