# Generated by Django 4.1.5 on 2023-01-16 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_client_createdon_alter_clientlog_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlog',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 16)),
        ),
    ]
