# Generated by Django 4.1.5 on 2023-01-22 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_clientlog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlog',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='createdon',
            field=models.DateField(default=datetime.date(2023, 1, 22)),
        ),
        migrations.AlterField(
            model_name='clientlog',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 22)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 22)),
        ),
    ]
