# Generated by Django 4.1 on 2023-04-24 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_clientlog_logout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='createdon',
            field=models.DateField(default=datetime.date(2023, 4, 24)),
        ),
        migrations.AlterField(
            model_name='clientlog',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 24)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 24)),
        ),
    ]
