# Generated by Django 4.1.5 on 2023-02-15 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_clientlog_logout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='createdon',
            field=models.DateField(default=datetime.date(2023, 2, 15)),
        ),
        migrations.AlterField(
            model_name='clientlog',
            name='date',
            field=models.DateField(default=datetime.date(2023, 2, 15)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date(2023, 2, 15)),
        ),
    ]
